### ISSUE TITLE
Cheroot 8.2.1 & 8.3.0 [abstract] tests fail in Python 3.8

### ISSUE THREAD

**Issue by unode** [cherrypy/cheroot#297] opened 2020-06-21 12:40 UTC
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
See original issue report on [Nixpkgs repository](https://github.com/NixOS/nixpkgs/issues/91220)
In nixpkgs tests must pass for a build to be successful. Currently two tests fail on Python 3.8.

❓ **What is the motivation / use case for changing the behavior?**
This seems to be a Python 3.8 issue. All tests pass in Python 3.7.

💡 **To Reproduce**
1. `git clone git@github.com:NixOS/nixpkgs-channels`
2. Install [nix or NixOS](https://nixos.org/download.html)
3. `nix-build -A python38Packages.cheroot`

💡 **Expected behavior**
All tests should pass

📋 **Details**
See original issue report on [Nixpkgs repository](https://github.com/NixOS/nixpkgs/issues/91220)

📋 **Environment**
See original issue report on [Nixpkgs repository](https://github.com/NixOS/nixpkgs/issues/91220)

- Cheroot version: 8.2.1 but also reproducible with 8.3.0
- CherryPy version: X.X.X (if applicable)
- Python version: 3.8.3
- OS: NixOS
- Browser: not applicable

**Comment by webknjaz** [comment] 2020-07-03 21:55
Hm... Didn't I patch that? Probably in CherryPy. Anyway, feel free to stick xfail on your side until this gets sorted out. The problem is that stdlib did some changes to urllib to have more strict input validation,  we'll probably have to monkey-patch that in our tests.

**Comment by webknjaz** [comment] 2020-07-03 21:56
P.S. It's not technically a bug in runtime, only in tests.

**Comment by unode** [comment] 2020-07-03 22:31
Currently working around the issue by disabling the affected tests https://github.com/NixOS/nixpkgs/pull/91322/commits/d0a87e749cfa3d8d274dff42320c5c8787badbed#diff-b6c67e4f109ba6de784a6250bca26429R58

**Comment by webknjaz** [comment] 2020-07-13 15:15
Duplicate of https://github.com/cherrypy/cheroot/issues/276.
Fixed by https://github.com/cherrypy/cheroot/pull/280 (https://github.com/cherrypy/cheroot/commit/6ead1efb37edfade4dda60e48d1af8fe89be3cdc).

Released as a part of [`cheroot==8.3.1`](https://pypi.org/project/cheroot/8.3.1/).

**Closed** 2020-07-13 15:16 UTC
Labels: good first issue, help wanted
