### ISSUE TITLE
A TLS-related traceback shows up during CherryPy startup on Windows 10

### ISSUE THREAD

**Issue by joaompinto** [cherrypy/cheroot#302] opened 2020-07-18 12:15 UTC
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

When attempting to run cherrypy with SSL I get the error:
```python-traceback
ConnectionAbortedError: [WinError 10053]
```

❓ **What is the motivation / use case for changing the behavior?**

Need an HTTPS listener

💡 **To Reproduce**
Run the folllowing script:
```python
import cherrypy

class RootServer:
    @cherrypy.expose
    def index(self, **keywords):
        return "it works!"

if __name__ == '__main__':
    server_config={
        'server.socket_host': '127.0.0.1',
        'server.socket_port': 8443,
        'server.ssl_certificate':'cert.pem',
        'server.ssl_private_key':'privkey.pem'
    }

    cherrypy.config.update(server_config)
    cherrypy.quickstart(RootServer())
```

📋 **Details**
```python-traceback
18/Jul/2020:14:01:24] ENGINE Started monitor thread 'Autoreloader'.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\lameg\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\lameg\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lameg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cheroot\ssl\builtin.py", line 72, in <lambda>
    target=lambda: context.wrap_socket(
  File "C:\Users\lameg\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\lameg\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\lameg\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[18/Jul/2020:14:01:24] ENGINE Serving on https://127.0.0.1:8443
```

📋 **Environment**
- CherryPy version: 18.6.0
- Python version: 3.8.3rc1
- OS: Windows 10

**Comment by webknjaz** [comment] 2020-07-18 18:36
Please fill out the issue template instead of removing it. It's not a bug report currently and I'll have to close it if there's no proof/repro/other required details.

**Comment by joaompinto** [comment] 2020-07-18 20:14
I am sorry I forgot to remove the comments when submitting.
Thanks for looking at it.

**Comment by webknjaz** [comment] 2020-07-18 22:47
I think you're hitting the Checker plugin of CherryPy that tries to connect over HTTP on startup. Disable it (`'checker.on': False`) and it'll not show up in logs.

**Comment by joaompinto** [comment] 2020-07-19 10:53
Adding 'checker.on': False did not resolve problem, can you please reopen the issue ?

Thanks

**Comment by webknjaz** [comment] 2020-07-19 17:14
@joaompinto re-opening but we'll need a full log and STR. Currently, you only added an incomplete part of the log and no pointers wrt what you did in order to see it. We need to make sure whether this is happening on startup or related to some HTTP requests you produce with a browser or any other HTTP client.

Also, since it's a cheroot repo, we need a cheroot-only reproducer, not involving CherryPy.

**Comment by webknjaz** [comment] 2020-07-19 17:15
Also, you say that you tried to turn off the checker but haven't shown any proof confirming how exactly you did that and so we don't know whether you applied it correctly or not.

**Comment by webknjaz** [comment] 2020-07-19 17:17
Plus are you sure you've generated the certificates correctly?
`ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine` suggests that something on your system interrupted the connection, I'd say it's related to your firewalls or whatever you have there.

**Comment by webknjaz** [comment] 2020-07-19 17:21
https://stackoverflow.com/a/51697893/595220 gives a few pointers to what to check on your computer. Also, [the docs say](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2):
> **WSAECONNABORTED**
> *10053*
> Software caused connection abort.
> An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error.

**Comment by webknjaz** [comment] 2020-07-19 17:23
> Also, you say that you tried to turn off the checker but haven't shown any proof confirming how exactly you did that and so we don't know whether you applied it correctly or not.

The fact that the traceback shows up even before the "listening" log line, confirms my suspicion that it's caused by the Checker tool.

**Comment by webknjaz** [comment] 2020-07-19 17:29
I think this is a duplicate of https://github.com/cherrypy/cheroot/issues/292. You're getting confused by the traceback showing up in the log but the presence of it does not mean that the setup does not work. I may mean that an incorrect or a client-interrupted request has been sent to the server.

**Comment by joaompinto** [comment] 2020-07-19 17:39
I did the test as I understood from your suggestion:
```
import cherrypy

class RootServer:
    @cherrypy.expose
    def index(self, **keywords):
        return "it works!"

if __name__ == '__main__':
    server_config={
        'server.socket_host': '127.0.0.1',
        'server.socket_port': 8443,
        'server.ssl_certificate':'cert.pem',
        'server.ssl_private_key':'privkey.pem',
        'checker.on': False
    }

    cherrypy.config.update(server_config)
    cherrypy.quickstart(RootServer())
```

I have generated the certificates correctly, and the exact same code works fine on Linux, without disabling the checker.

**Comment by webknjaz** [comment] 2020-07-19 17:45
What about the rest of the questions? Something is clearly doing the request.

**Comment by joaompinto** [comment] 2020-07-19 17:46
I have raised the issue for "cheroot" because as per the backtrace the error is reported at:
lib\site-packages\cheroot\ssl\builtin.py", line 72
Do you really think it makes sense to report it for CherryPy instead ?

If you believe that my code or my setup are not correct, can you please show me a sample that works on Windows ? 
You bring questions and research on issues not directly related but I don't see an effort on your part on reproducing my issue. If you dot not have access to a Windows10 I am available to test whatever code you believe to be the right one to setup an SSL listener on cherrypy.

**Comment by joaompinto** [comment] 2020-07-19 17:47
I am not doing any kind of request, there is no client involved from my side, I am just starting the piece of code which I have pasted.

**Comment by Safihre** [comment] 2020-07-19 20:21
@webknjaz I am seeing the same traceback on Windows with all our SABnzbd clients that have HTTPS enabled. 
It only started to happen after I updated our dependencies, so I think it has to do with https://github.com/cherrypy/cheroot/pull/291

**Comment by webknjaz** [comment] 2020-07-19 20:25
@joaompinto
1) Let's keep the issue here for now, I'll transfer it later if needed.
2) *I think* that something does make the request.
3) Your setup does look okay but I have no way of reproducing it since I haven't used Windows in ages and don't have it in my possession. Although, we do have some TLS-related tests in our CIs that run on Windows. One thing I noticed is that you run 32-bit Python for some reason (is this intentional?) and we only test under 64-bit.
4) My questions are directly related to this issue based on reports I've seen in the past, even if they may seem unobvious to you.
5) We need towards making a Cheroot-only reproducer to eliminate the possibility of CherryPy influence.

**Comment by webknjaz** [comment] 2020-07-19 20:28
@Safihre ah! I forgot about it... You must be right, let's tag @mxi-ca and see if he has any thoughts. Honestly, since nobody on the team has Windows, these things may stay unnoticed.

So now I'm convinced that this is what's happening: https://github.com/cherrypy/cheroot/issues/302#issuecomment-660679101.

**Comment by Safihre** [comment] 2020-07-19 20:28
@webknjaz Let help:
```python
    from cheroot import wsgi


    def my_crazy_app(environ, start_response):
        status = '200 OK'
        response_headers = [('Content-type', 'text/plain')]
        start_response(status, response_headers)
        return [b'Hello world!']


    addr = '0.0.0.0', 8070
    server = wsgi.Server(addr, my_crazy_app)

    # the SSL stuff:
    from cheroot.server import get_ssl_adapter_class

    server.ssl_adapter = get_ssl_adapter_class(name='builtin')(r'C:\Users\saf\AppData\Local\sabnzbd\admin\server.cert', r'C:\Users\saf\AppData\Local\sabnzbd\admin\server.key')

    server.start()
```

Results in:
```
Traceback (most recent call last):
  File "C:\Users\saf\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\saf\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\saf\Documents\GitHub\sabnzbd3\venv\lib\site-packages\cheroot\ssl\builtin.py", line 68, in <lambda>
    target=lambda: context.wrap_socket(
  File "C:\Users\saf\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\saf\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\saf\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```

**Comment by Safihre** [comment] 2020-07-19 20:37
@webknjaz actually scratch my comment about #291, when I retry it using `cheroot==8.3.0` it also happens! Guess I just didn't notice it until now..

**Comment by Safihre** [comment] 2020-07-19 20:39
@webknjaz actually scratch my comment about #291, when I retry it using `cheroot==8.3.0` it also happenned.
The problem was introduced in `8.3.0`. 
On `8.2.1` it does not occur. 
So it is introduced by https://github.com/cherrypy/cheroot/pull/243

**Comment by webknjaz** [comment] 2020-07-19 21:28
Is the exception happening inside the thread? https://github.com/cherrypy/cheroot/blob/a9b6643/cheroot/ssl/builtin.py#L72-L75

**Comment by webknjaz** [comment] 2020-07-19 21:34
@Safihre could you please check what's the exception happening under Python 2?

**Comment by webknjaz** [comment] 2020-07-19 22:35
I *think* we need to do something like https://github.com/python/cpython/pull/9713/files#diff-e4b38b263c67d9ca87c5fa4a8fb1aba7R139. It suggests that `ConnectionAbortedError`, `BrokenPipeError` and `ConnectionResetError` may be safely ignored. I think I'd also add `InterruptedError` to that list too.

There's a few questions left unanswered, though:
1) We need a stable reproducer integrated into `cheroot/test/test_ssl.py`.
2) The above exceptions are Python 3 only, how to handle Python 2 in this case? (requires somebody to experiment and see what errors are being raised.
3) Is the socket closed or does it need closing if any of those exceptions managed to happen? Should it be determined dynamically?

N.B. Here's another interesting piece of explanation: https://github.com/python/cpython/blob/8e836bb21ce73f0794fd769db5883c29680dfe47/Lib/test/test_ssl.py#L2335-L2345.

**Comment by Safihre** [comment] 2020-07-20 06:28
@webknjaz To answer the questions:
Yes, it happens in [those lines/thread](https://github.com/cherrypy/cheroot/blob/a9b6643/cheroot/ssl/builtin.py#L72-L75).
We are now also using Python 3 only for SABnzbd, but I took a quick look on Python 2 and no error is thrown. Seems the code is Python 3 specific anyway based on [this comment](https://github.com/cherrypy/cheroot/blob/a9b6643/cheroot/ssl/builtin.py#L62)?
I thought CherryPy dropped Python 2 support anyway?

I want to help fix this, but right now I am not sure yet what this code is supposed to do? Provide some certificate information it seems?

**Comment by webknjaz** [comment] 2020-07-20 15:29
@Safihre yeah, basically this code creates a client connection and tries to read some details that the server-side sends over the wire as it's visible from the client-side. This is a one-time action on startup and the collected information is populated into the WSGI env.
The client connection is performed from the main thread and the server-side socket sits in a temporary thread. When the client connection closes, the server connection seems to explode sometimes. The server-side code that runs in a thread is wrapped into a lambda. So you take out that lambda and declare it as a function, and inside that function add try/except ignoring these specific exceptions.

CherryPy did drop Python 2, but Cheroot not yet. I want to do this after the HTTP parser refactoring and addressing these regressions.

@mxii-ca could you remind me why that code needs a client-server connection vs reading the certificate from the provided files?

**Comment by mxii-ca** [comment] 2020-07-21 22:28
currently, the builtin ssl module does not publicly expose a way to parse a certificate directly, however, it has a _private_ test method for parsing a certificate file and it exposes an interface for parsing certificates used in an active connection

as such, when I improved the WSGI environment variable coverage for the builtin ssl module I coded it to use the more public, indirect way by creating a loopback connection and performing the ssl handshake to parse the cert (``_loopback_for_cert``), though, as loopback connections are only available in Python 3.0+ for Unix and Python 3.5+ for Windows, I had the code fallback to the hidden test method, suppressing all errors due to not being guaranteed (``_parse_cert``)

while we could add code that parses the certificate directly, I wouldn't want to maintain it when there is a viable alternative that works well enough. I would also be reluctant to add a new dependency... it is only used to populate WSGI environment variables about the server's own certificate, something that is rare for WSGI apps to care about (needing access to the client cert was my use case for the original MR)

another possibility is promoting the test method to be used first, falling back to the loopback connection if it isn't present or if it fails. this would be more efficient (not needing a connection or a tls handshake) but it kinda feels wrong to use the hidden test method in the first place

----

as for the ``ConnectionAbortedError``, my hunch is: TLS 1.3 streamlines the handshake in such a way that switches the last handshake packet from being sent from the server to one being sent from the client, if the client is closing the connection fast enough after sending that last packet, the OS may set the FIN flag on that packet to close the connection or even decide to drop the packet and just close the connection with a FIN only flag resulting in the server having the connection closed before the handshake completes... 

this would seem to correlate with the traceback posted above as having come from the thread as it is the thread that runs the server side of the connection. however, I should also note that the client side code already ignores all ``OSError`` (falling back to the test method) so it could conceivably be happening there too without us noticing

I would need to examine a tcp dump of a reproduction to confirm that this is the case

at any rate, I agree that the exception can be safely ignored, I'd probably go as far as ignoring all ``OSError``

**Comment by mxii-ca** [comment] 2020-07-22 17:43
I was able to reproduce this on Windows 10 2004 with Python 3.8.5 using the code above and grab a Wireshark capture:
in my case, it used TLS 1.3 and both the Server Handshake Finished and Client Handshake Finished messages are sent and ack'd.
the client then proceeds to send a FIN to close the connection at which point the server sends back a TLS session ticket.
even though the client has not yet received a FIN, it treats the connection as closed sending a RST in response to the session ticket, and thus the connection aborted error

as the session ticket is supposed to be sent as a separate post handshake message at some unspecified time, the client does not need to wait to receive it before closing the connection, but the server treats it as an error. many of TLS 1.3's features are still unsupported by Python and as such, there is no easy way to wait for the session tickets to be received by the client

in my testing, it appears that sending some data from the server and having the client wait for the data is long enough for the server to send the session tickets (and the connection gets closed cleanly with bi-directional FINs), however, this is ultimately a race condition and this small delay won't work in all cases
```
def _loopback_for_cert_thread(context, server):
    with context.wrap_socket(
            server, do_handshake_on_connect=True, server_side=True,
    ) as ssl_sock:
        ssl_sock.send(b'0000')

def _loopback_for_cert(certificate, private_key, certificate_chain):
    """Create a loopback connection to parse a cert with a private key."""
    context = ssl.create_default_context(cafile=certificate_chain)
    context.load_cert_chain(certificate, private_key)
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE

    # Python 3+ Unix, Python 3.5+ Windows
    client, server = socket.socketpair()
    try:
        # `wrap_socket` will block until the ssl handshake is complete.
        # it must be called on both ends at the same time -> thread
        # openssl will cache the peer's cert during a successful handshake
        # and return it via `getpeercert` even after the socket is closed.
        # when `close` is called, the SSL shutdown notice will be sent
        # and then python will wait to receive the corollary shutdown.
        thread = threading.Thread(
            target=_loopback_for_cert_thread, args=(context, server)
        )
        try:
            thread.start()
            with context.wrap_socket(
                    client, do_handshake_on_connect=True,
                    server_side=False,
            ) as ssl_sock:
                ssl_sock.recv(4)
                return ssl_sock.getpeercert()
        finally:
            thread.join()
    finally:
        client.close()
        server.close()
```

**Comment by webknjaz** [comment] 2020-07-22 21:19
@mxii-ca thanks for the detailed analysis. Should we expect that you'll send a PR with that? Should this approach be combined with ignoring `OSError`?

**Closed** 2020-07-26 19:06 UTC
Labels: Windows, bug, help wanted, regression, reproducer: present
