### ISSUE TITLE
tox -e pre-commit fails attempting to build cryptography < 3.3

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#631] opened 2023-05-20 13:08 UTC
Today I tried to run the pre-commits, but the build env fails:

```
 cheroot reuse-port $ tox -e pre-commit
pre-commit: install_deps> .tox/pre-commit/bin/python -bb -E -s /Users/jaraco/code/cherrypy/cheroot/bin/pip-wrapper pre-commit /Users/jaraco/code/cherrypy/cheroot/requirements/ install -r requirements/tox-pre-commit.in
.pkg: _optional_hooks> python /Users/jaraco/.local/pipx/venvs/tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_editable> python /Users/jaraco/.local/pipx/venvs/tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /Users/jaraco/.local/pipx/venvs/tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_editable> python /Users/jaraco/.local/pipx/venvs/tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
pre-commit: install_package_deps> .tox/pre-commit/bin/python -bb -E -s /Users/jaraco/code/cherrypy/cheroot/bin/pip-wrapper pre-commit /Users/jaraco/code/cherrypy/cheroot/requirements/ install 'importlib-metadata; python_version < "3.8"' jaraco.functools 'more-itertools>=2.6'
pre-commit: install_package> .tox/pre-commit/bin/python -bb -E -s /Users/jaraco/code/cherrypy/cheroot/bin/pip-wrapper pre-commit /Users/jaraco/code/cherrypy/cheroot/requirements/ install --force-reinstall --no-deps /Users/jaraco/code/cherrypy/cheroot/.tox/.tmp/package/5/cheroot-9.0.1.dev771+g081aa090-0.editable-py3-none-any.whl
pre-commit: commands[0]> pre-commit run --all-files --show-diff-on-failure
[INFO] Initializing environment for https://github.com/asottile/add-trailing-comma.git.
[INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.git.
[INFO] Initializing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.git.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.git:darglint ~= 1.8.1,flake8-2020 ~= 1.7.0,flake8-annotations ~= 2.7.0; python_version < "3.7",flake8-annotations ~= 2.9.1; python_version >= "3.7",flake8-docstrings ~= 1.6.0,flake8-length ~= 0.3.0,flake8-logging-format ~= 0.7.5,flake8-pytest-style ~= 1.6.0,flake8-spellcheck ~= 0.26.0; python_version < "3.8",flake8-spellcheck ~= 0.28.0; python_version >= "3.8".
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.git.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.git:cryptography < 3.3,lxml,types-backports,types-pyOpenSSL,types-requests.
[INFO] Initializing environment for https://github.com/PyCQA/pylint.git.
[INFO] Initializing environment for https://github.com/PyCQA/pylint.git:Sphinx,jaraco.context,jaraco.functools,jaraco.text,more_itertools,portend,pylint-pytest < 1.1.0,pypytools,requests_toolbelt,requests_unixsocket.
[INFO] Installing environment for https://github.com/asottile/add-trailing-comma.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/Lucas-C/pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/Lucas-C/pre-commit-hooks-markup.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/Lucas-C/pre-commit-hooks-lxml.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/jaraco/.cache/pre-commit/repozsmpld_5/py_env-python3.11/bin/python', '-mpip', 'install', '.', 'cryptography < 3.3', 'lxml', 'types-backports', 'types-pyOpenSSL', 'types-requests')
return code: 1
expected return code: 0
stdout:
    Processing /Users/jaraco/.cache/pre-commit/repozsmpld_5
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting cryptography<3.3
      Downloading cryptography-3.2.1.tar.gz (540 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 541.0/541.0 kB 4.5 MB/s eta 0:00:00
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting lxml
      Using cached lxml-4.9.2-cp311-cp311-macosx_13_0_arm64.whl
    Collecting types-backports
      Using cached types_backports-0.1.3-py2.py3-none-any.whl (2.2 kB)
    Collecting types-pyOpenSSL
      Downloading types_pyOpenSSL-23.1.0.3-py3-none-any.whl (7.0 kB)
    Collecting types-requests
      Using cached types_requests-2.30.0.0-py3-none-any.whl (14 kB)
    Collecting mypy==1.1.1 (from pre-commit-placeholder-package==0.0.0)
      Using cached mypy-1.1.1-cp311-cp311-macosx_11_0_arm64.whl (9.6 MB)
    Collecting typing-extensions>=3.10 (from mypy==1.1.1->pre-commit-placeholder-package==0.0.0)
      Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
    Collecting mypy-extensions>=1.0.0 (from mypy==1.1.1->pre-commit-placeholder-package==0.0.0)
      Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
    Collecting six>=1.4.1 (from cryptography<3.3)
      Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
    Collecting cffi!=1.11.3,>=1.8 (from cryptography<3.3)
      Using cached cffi-1.15.1-cp311-cp311-macosx_11_0_arm64.whl (174 kB)
    INFO: pip is looking at multiple versions of types-pyopenssl to determine which version is compatible with other requirements. This could take a while.
    Collecting types-pyOpenSSL
      Downloading types_pyOpenSSL-23.1.0.2-py3-none-any.whl (6.9 kB)
      Downloading types_pyOpenSSL-23.1.0.1-py3-none-any.whl (6.9 kB)
      Downloading types_pyOpenSSL-23.1.0.0-py3-none-any.whl (6.9 kB)
      Downloading types_pyOpenSSL-23.0.0.4-py3-none-any.whl (6.9 kB)
      Downloading types_pyOpenSSL-23.0.0.3-py3-none-any.whl (6.9 kB)
      Downloading types_pyOpenSSL-23.0.0.2-py3-none-any.whl (6.8 kB)
      Downloading types_pyOpenSSL-23.0.0.1-py3-none-any.whl (6.8 kB)
    INFO: pip is looking at multiple versions of types-pyopenssl to determine which version is compatible with other requirements. This could take a while.
      Downloading types_pyOpenSSL-23.0.0.0-py3-none-any.whl (6.7 kB)
    Collecting types-cryptography (from types-pyOpenSSL)
      Using cached types_cryptography-3.3.23.2-py3-none-any.whl (30 kB)
    Collecting types-urllib3 (from types-requests)
      Using cached types_urllib3-1.26.25.13-py3-none-any.whl (15 kB)
    Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography<3.3)
      Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
    Building wheels for collected packages: pre-commit-placeholder-package, cryptography
      Building wheel for pre-commit-placeholder-package (setup.py): started
      Building wheel for pre-commit-placeholder-package (setup.py): finished with status 'done'
      Created wheel for pre-commit-placeholder-package: filename=pre_commit_placeholder_package-0.0.0-py3-none-any.whl size=2048 sha256=5feae8b19454d50dd8d21545f32c2ea88df05a36c486a48556b8f14b3619144d
      Stored in directory: /private/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-ephem-wheel-cache-ux_tr4vw/wheels/df/78/50/28ff0b6601208068d6da8a3c9f6ac2fc39f34eb5c3438e6a01
      Building wheel for cryptography (pyproject.toml): started
      Building wheel for cryptography (pyproject.toml): finished with status 'error'
    Successfully built pre-commit-placeholder-package
    Failed to build cryptography
    
stderr:
      error: subprocess-exited-with-error
      
      × Building wheel for cryptography (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [144 lines of output]
          running bdist_wheel
          running build
          running build_py
          creating build
          creating build/lib.macosx-13-arm64-cpython-311
          creating build/lib.macosx-13-arm64-cpython-311/cryptography
          copying src/cryptography/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography
          copying src/cryptography/utils.py -> build/lib.macosx-13-arm64-cpython-311/cryptography
          copying src/cryptography/__about__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography
          copying src/cryptography/exceptions.py -> build/lib.macosx-13-arm64-cpython-311/cryptography
          copying src/cryptography/fernet.py -> build/lib.macosx-13-arm64-cpython-311/cryptography
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat
          copying src/cryptography/hazmat/_der.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat
          copying src/cryptography/hazmat/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat
          copying src/cryptography/hazmat/_oid.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/oid.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/ocsp.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/general_name.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/extensions.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/name.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/base.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          copying src/cryptography/x509/certificate_transparency.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/x509
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends
          copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends
          copying src/cryptography/hazmat/backends/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          copying src/cryptography/hazmat/primitives/padding.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/bindings
          copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/bindings
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/ocsp.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/backends/openssl
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/kdf
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/twofactor
          copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/twofactor
          copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/twofactor
          copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/twofactor
          copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/twofactor
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/serialization
          copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/serialization
          copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/serialization
          copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/serialization
          copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/serialization
          copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/serialization
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/ciphers
          copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/ciphers
          copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/ciphers
          copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/ciphers
          copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/ciphers
          copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/ciphers
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/primitives/asymmetric
          creating build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/bindings/openssl
          copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/bindings/openssl
          copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/bindings/openssl
          copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.macosx-13-arm64-cpython-311/cryptography/hazmat/bindings/openssl
          running egg_info
          writing src/cryptography.egg-info/PKG-INFO
          writing dependency_links to src/cryptography.egg-info/dependency_links.txt
          writing requirements to src/cryptography.egg-info/requires.txt
          writing top-level names to src/cryptography.egg-info/top_level.txt
          reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
          reading manifest template 'MANIFEST.in'
          no previously-included directories found matching 'docs/_build'
          warning: no previously-included files found matching 'vectors'
          warning: no previously-included files matching '*' found under directory 'vectors'
          warning: no previously-included files found matching '.travis.yml'
          warning: no previously-included files found matching '.travis'
          warning: no previously-included files matching '*' found under directory '.travis'
          warning: no previously-included files matching '*' found under directory '.github'
          warning: no previously-included files found matching 'release.py'
          warning: no previously-included files found matching '.coveragerc'
          warning: no previously-included files found matching 'codecov.yml'
          warning: no previously-included files found matching 'dev-requirements.txt'
          warning: no previously-included files found matching 'rtd-requirements.txt'
          warning: no previously-included files found matching 'tox.ini'
          warning: no previously-included files matching '*' found under directory '.zuul.d'
          warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
          adding license file 'LICENSE'
          adding license file 'LICENSE.APACHE'
          adding license file 'LICENSE.BSD'
          adding license file 'LICENSE.PSF'
          adding license file 'AUTHORS.rst'
          writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
          warning: build_py: byte-compiling is disabled, skipping.
          
          running build_ext
          generating cffi module 'build/temp.macosx-13-arm64-cpython-311/_padding.c'
          creating build/temp.macosx-13-arm64-cpython-311
          generating cffi module 'build/temp.macosx-13-arm64-cpython-311/_openssl.c'
          building '_openssl' extension
          creating build/temp.macosx-13-arm64-cpython-311/build
          creating build/temp.macosx-13-arm64-cpython-311/build/temp.macosx-13-arm64-cpython-311
          clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/Users/jaraco/.cache/pre-commit/repozsmpld_5/py_env-python3.11/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c build/temp.macosx-13-arm64-cpython-311/_openssl.c -o build/temp.macosx-13-arm64-cpython-311/build/temp.macosx-13-arm64-cpython-311/_openssl.o -Wconversion -Wno-error=sign-conversion
          build/temp.macosx-13-arm64-cpython-311/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found
          #include <openssl/opensslv.h>
                   ^~~~~~~~~~~~~~~~~~~~
          1 error generated.
          error: command '/usr/bin/clang' failed with exit code 1
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for cryptography
    ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
    
Check the log at /Users/jaraco/.cache/pre-commit/pre-commit.log
pre-commit: exit 3 (34.78 seconds) /Users/jaraco/code/cherrypy/cheroot> pre-commit run --all-files --show-diff-on-failure pid=18858
.pkg: _exit> python /Users/jaraco/.local/pipx/venvs/tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  pre-commit: FAIL code 3 (37.71=setup[2.93]+cmd[34.78] seconds)
  evaluation failed :( (37.83 seconds)
```

I can replicate the error by attempting to simply `pip install 'cryptography<3.3'`.

**Comment by webknjaz** [comment] 2023-05-21 01:45
This is interesting... Obviously, I'm not seeing this because of the different environment +I don't use macs.
I've seen some other projects specifically running various "dev env" commands in CI to make sure that they are still usable for the contributors. And I've been meaning to start doing the same.


Also, as a part of my CI stability effort, I've made a number of env-specific "lockfiles" like https://github.com/cherrypy/cheroot/blob/main/requirements/tox-pre-commit-cp311-linux-x86_64.txt but only the main test env constraints are set up to be generated for all the factor combinations. So the pins for the "linting" envs only exist for linux at the moment.
You could generate the macos ones using pip-tools and they'll be picked up automatically in tox, provided that the filename follows the pattern.

Unfortunately, this doesn't apply to the venvs managed by pre-commit itself (which is a known design limitation of that project).

I'll try to look into it but you should be able to build cryptography by providing CFLAGS pointing at the openssl headers..

The reason this version doesn't pick up the wheels is that it's old and was published long before Python 3.11 was a thing.

As a workaround, you could try forcing a different version of Python through for tox to use. You could also try installing pre-commit under an older Python version through something like pipx and run it directly.

**Comment by webknjaz** [comment] 2023-05-21 01:50
Apparently, it was pinned for Python 3.5 compatibility:
https://github.com/cherrypy/cheroot/blob/f82aee6/.pre-commit-config.yaml#LL129C25-L129C25. It probably just needs to be made compatible with py38 now.

**Comment by webknjaz** [comment] 2023-06-27 20:38
Closing this as a duplicate of #637.

**Closed by webknjaz** 2023-06-27 20:38 UTC
Labels: bug, triage

**Comment by jaraco** [comment] 2023-06-28 13:11
Oops. Sorry for the dupe.
