### ISSUE TITLE
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:897)

### ISSUE THREAD

**Issue by nizamial09** [cherrypy/cheroot#347] opened 2020-12-08 14:22 UTC
I was using the https based ceph-dashboard and I keep getting this error notification in the log continously. 

```
mgr[dashboard] [04/Dec/2020:05:20:43] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
 File "/lib/python3.6/site-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
 self.tick()
File "/lib/python3.6/site-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
 s, ssl_env = self.ssl_adapter.wrap(s)
File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 131, in wrapper
return func(self, sock)
File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 92, in wrapper
 return func(self, sock)
File "/lib/python3.6/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
server_side=True)
File "/lib64/python3.6/ssl.py", line 365, in wrap_socket
 _context=self, _session=session)
File "/lib64/python3.6/ssl.py", line 776, in __init__
self.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:897)
```
-->

❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

❓ **What is the motivation / use case for changing the behavior?**

💡 **To Reproduce**

1. Run '...'
2. Make request '....'
3. See error

💡 **Expected behavior**

📋 **Details**

📋 **Environment**

- Cheroot version: X.X.X
- CherryPy version: X.X.X (if applicable)
- Python version: 3.8.X
- OS: XXX
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

📋 **Additional context**

**Comment by webknjaz** [comment] 2020-12-08 14:28
This doesn't make sense to use because it doesn't contain any details.

**Comment by webknjaz** [comment] 2020-12-08 14:29
Duplicate of #346

**Closed by webknjaz** 2020-12-08 14:29 UTC
Labels: invalid

**Comment by webknjaz** [comment] 2020-12-08 14:31
Also, the traceback doesn't look like any version we ship.
