### ISSUE TITLE
with "-X dev": ResourceWarning: unclosed <ssl.SSLSocket fd=4 ...

### ISSUE THREAD

**Issue by sanderjo** [cherrypy/cheroot#290] opened 2020-06-05 08:15 UTC
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
With `python3 -X dev -X tracemalloc=5` on cheroot code with SSL, python gives a ResourceWarning

❓ **What is the motivation / use case for changing the behavior?**

A python ResourceWarning is an good indication code can be improved: it's not closing a resource.
It generates warnings in other code (SABnzbd) this is using cherrypy / cheroot (when running that code with `-X dev`), which makes cleaning up own code more difficult.

💡 **To Reproduce**

```
$ python3 -X dev -X tracemalloc=5 cheroot_only.py 
/usr/lib/python3.8/threading.py:870: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  self._target(*self._args, **self._kwargs)
Object allocated at (most recent call last):
  File "/usr/lib/python3.8/threading.py", lineno 932
    self.run()
  File "/usr/lib/python3.8/threading.py", lineno 870
    self._target(*self._args, **self._kwargs)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 68
    target=lambda: context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", lineno 500
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", lineno 1003
    self = cls.__new__(cls, **kwargs)
/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py:75: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  return context.wrap_socket(
Object allocated at (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 198
    _parse_cert(certificate, private_key, self.certificate_chain),
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 94
    return _loopback_for_cert(certificate, private_key, certificate_chain)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 75
    return context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", lineno 500
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", lineno 1003
    self = cls.__new__(cls, **kwargs)
```
with this code:
```
#!/usr/bin/python3

from cheroot import wsgi
def my_crazy_app(environ, start_response):
    status = '200 OK'
    response_headers = [('Content-type','text/plain')]
    start_response(status, response_headers)
    return [b'Hello world!']
addr = '0.0.0.0', 8070
server = wsgi.Server(addr, my_crazy_app)

# the SSL stuff:
from cheroot.server import get_ssl_adapter_class
server.ssl_adapter = get_ssl_adapter_class(name='builtin')('./server.cert', './server.key')

server.start()
```

💡 **Expected behavior**
No ResourceWarning

📋 **Details**
See above

📋 **Environment**

- Cheroot version: 8.3.0
- CherryPy version: 18.5.0
- Python version: 3.8
- OS: Ubuntu 20.04
- Browser: not involved to get ResourceWarning

📋 **Additional context**

Related to https://github.com/sabnzbd/sabnzbd/issues/1489

**Comment by webknjaz** [comment] 2020-06-06 07:35
Is this reproducible with pure Cheroot? (without CherryPy)
Here's how you can test it: https://github.com/cherrypy/cheroot/blob/8ff6998/cheroot/wsgi.py#L5-L15

**Comment by webknjaz** [comment] 2020-06-06 07:43
Looks like this is happening in code contributed in #243 by @mxii-ca and there's no code for closing the socket...

**Comment by sanderjo** [comment] 2020-06-06 07:50
> Is this reproducible with pure Cheroot? (without CherryPy)
> Here's how you can test it: https://github.com/cherrypy/cheroot/blob/8ff6998/cheroot/wsgi.py#L5-L15

I see no SSL code in that snippet. And the SSL is the essential part, I would say. Do you have a pointer to such code with SSL?

**Comment by webknjaz** [comment] 2020-06-06 08:09
Ah, right, sorry. I overlooked that. Inject something like
```python
from cheroot.server import get_ssl_adapter_class
httpserver.ssl_adapter = get_ssl_adapter_class(name='builtin')('./server.cert', './server.key')
```
before `.start()`

**Comment by sanderjo** [comment] 2020-06-06 08:15
Thanks, that helped. 
And, yes, ResourceWarning:

```
$ python3.8 -X dev -X tracemalloc=5 cheroot_only.py 
/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py:75: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  return context.wrap_socket(
Object allocated at (most recent call last):
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 198
    _parse_cert(certificate, private_key, self.certificate_chain),
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 94
    return _loopback_for_cert(certificate, private_key, certificate_chain)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 75
    return context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", lineno 500
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", lineno 1003
    self = cls.__new__(cls, **kwargs)
/usr/lib/python3.8/threading.py:870: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  self._target(*self._args, **self._kwargs)
Object allocated at (most recent call last):
  File "/usr/lib/python3.8/threading.py", lineno 932
    self.run()
  File "/usr/lib/python3.8/threading.py", lineno 870
    self._target(*self._args, **self._kwargs)
  File "/home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py", lineno 68
    target=lambda: context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", lineno 500
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", lineno 1003
    self = cls.__new__(cls, **kwargs)
```

with pure cheroot code:
```
#!/usr/bin/python3

if True:
    from cheroot import wsgi
    def my_crazy_app(environ, start_response):
        status = '200 OK'
        response_headers = [('Content-type','text/plain')]
        start_response(status, response_headers)
        return [b'Hello world!']
    addr = '0.0.0.0', 8070
    server = wsgi.Server(addr, my_crazy_app)
    
    from cheroot.server import get_ssl_adapter_class
    server.ssl_adapter = get_ssl_adapter_class(name='builtin')('./server.cert', './server.key')
    
    
    server.start()
```

**Comment by webknjaz** [comment] 2020-06-06 08:31
Why `if True`?

**Comment by sanderjo** [comment] 2020-06-06 08:32
> Why `if True`?

Ah, yes, sorry: because the example you gave was indented, and I was too lazy to solve that. I will do that now. BRB

**Comment by webknjaz** [comment] 2020-06-06 08:33
Mind updating the issue at the top with the new repro?

**Comment by webknjaz** [comment] 2020-06-06 08:34
Also, it'd be great to have a PR with the reproducer as a pytest based test.

Ref: https://pganssle-talks.github.io/xfail-lightning/

**Comment by sanderjo** [comment] 2020-06-06 08:45
> Also, it'd be great to have a PR with the reproducer as a pytest based test.
> 
> Ref: https://pganssle-talks.github.io/xfail-lightning/

Normal `pytest` setup? I did a quick test on the existing test stuff, but no go, so hint appreciated.
```
~/git/cheroot$ pytest cheroot/test/test_wsgi.py 
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --numprocesses=auto --testmon --cov=cheroot --cov-report --cov-report xml cheroot/test/test_wsgi.py
  inifile: /home/sander/git/cheroot/pytest.ini
  rootdir: /home/sander/git/cheroot
```

**Comment by webknjaz** [comment] 2020-06-06 08:49
Well, you don't have the test deps. It's wrapped with `tox` which takes care of deps and test virtualenvs. Just run `tox` to run all the tests and `tox -- cheroot/test/test_wsgi.py` is how you can bypass extra args to `pytest`.

**Comment by webknjaz** [comment] 2020-06-06 08:51
I was having in mind using the [`recwarn` fixture](https://docs.pytest.org/en/latest/warnings.html#recwarn) and checking that no ResourceWarnings are recorded.

**Comment by sanderjo** [comment] 2020-06-06 09:08
tox: got it installed, but first two tests already fail:

`tox -- cheroot/test/test_wsgi.py` gives

```
  -> Got sha from git/hg
==> Preparing upload
Error: Missing repository upload token

```


and

`tox -- cheroot/test/test_ssl.py `gives

```
Results (13.22s):
      46 passed
       2 failed
         - cheroot/test/test_ssl.py:212 test_tls_client_auth[VerifyMode.CERT_OPTIONAL-False-localhost-builtin]
         - cheroot/test/test_ssl.py:212 test_tls_client_auth[VerifyMode.CERT_REQUIRED-False-localhost-builtin]
ERROR: InvocationError for command /home/sander/git/cheroot/.tox/python/bin/pytest --testmon-off cheroot/test/test_ssl.py (exited with code 1)
______________________________________________________________________________ summary _______________________________________________________________________________
ERROR:   python: commands failed



```

So a bit hard to build new testing on that.

**Comment by sanderjo** [comment] 2020-06-06 09:08
> I was having in mind using the [`recwarn` fixture](https://docs.pytest.org/en/latest/warnings.html#recwarn) and checking that no ResourceWarnings are recorded.

Nice. I have to chew on that.

**Comment by webknjaz** [comment] 2020-06-06 09:14
Ignore the coverage upload error. It's not supposed to work outside of the CI.

As for `test_ssl`, there's a lot of weird cases where it fails depending on the TLS backend lib flavor (OpenSSL vs LibreSSL) and version (0.9/1.0/1.1 etc.). And also some tests fail flakily in slow envs too, like macOS and Windows.

**Comment by mxii-ca** [comment] 2020-06-06 19:21
IMO, this isn't something to be concerned about, python is just really aggressive when it comes to resource warnings

the thread created by `_loopback_for_cert` wraps a socket in ssl and does not call close on the wrapper; hence the `ssl.SSLSocket` `ResourceWarning` emitted when the thread exits.
However, the underlying socket is closed back in the main thread in the finally block at the end of `_loopback_for_cert`

changing `_loopback_for_cert` as follows gets rid of the pesky resource warnings:
```python
    client, server = socket.socketpair()
    try:
        thread = threading.Thread(
            target=lambda: context.wrap_socket(
                server, do_handshake_on_connect=True,
                server_side=True,
            ).close(),
        )
        try:
            thread.start()
            with context.wrap_socket(
                    client, do_handshake_on_connect=True,
                    server_side=False,
            ) as ssl_sock:
                return ssl_sock.getpeercert()
        finally:
            thread.join()
    finally:
        client.close()
        server.close()
```
note, however, that I have not done any testing (even pytest) beyond the reproducible example in the description

**Comment by sanderjo** [comment] 2020-06-06 20:31
@mxii-ca I tried, and no more ResourceWarning. Cool!

```
$ python3 -X dev -X tracemalloc=5 cheroot_only.py 


```
(thus: no warning)

```
$ diff /home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py.ORG /home/sander/.local/lib/python3.8/site-packages/cheroot/ssl/builtin.py
65,66d64
<         # ssl handshake is blocking and needs to happen on
<         # both ends at the same time so use a thread
71c69
<             ),
---
>             ).close(),
75,78c73,77
<             return context.wrap_socket(
<                 client, do_handshake_on_connect=True,
<                 server_side=False,
<             ).getpeercert()
---
>             with context.wrap_socket(
>                     client, do_handshake_on_connect=True,
>                     server_side=False,
>             ) as ssl_sock:
>                 return ssl_sock.getpeercert()
```

**Comment by webknjaz** [comment] 2020-06-06 21:53
@mxii-ca @sanderjo yeah, I know that Python tracks resources like that, and even though this leakage is minor, I'd like to have it closed correctly. So a PR would be appreciated.

**Closed** 2020-06-11 10:07 UTC
Labels: bug, reproducer: present
