### ISSUE TITLE
SABnzbd randomly stops working

### ISSUE THREAD

**Issue by dguilloryjr** [cherrypy/cheroot#713] opened 2024-05-21 15:05 UTC
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
Random times through out the day SABnzb stops working. Stops working meaning the web site will not pull up Sonarr as well as Radarr report they cannot communicate to SABnzbd. 

❓ **What is the motivation / use case for changing the behavior?**
I am having to restart SABnzbd constantly everyday multiple times a day

💡 **To Reproduce**
Not sure how to reproduce I just start the service the only way I usually know its not working is when a show that evening does not download. 
 
Nothing specific to call out here, just let the service run. From chat in discord looks like someone figured out to many ques then the webservice dies. 

💡 **Expected behavior**
just to function as designed. 

📋 **Details**
I attached a log file to this bug
[sabnzbd.log](https://github.com/cherrypy/cheroot/files/15391697/sabnzbd.log)

📋 **Environment**
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎10/‎5/‎2022
OS build	22631.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

📋 **Additional context**
I attached a log file to this bug
[sabnzbd.log](https://github.com/cherrypy/cheroot/files/15391697/sabnzbd.log)

**Comment by webknjaz** [comment] 2024-05-22 01:51
Hello, we need a Cheroot-specific repro as we have no knowledge of your third-party app and therefore no ability to understand what you want 🤷‍♂️

**Comment by thezoggy** [comment] 2024-05-24 04:08
dupe of #710 - feel free to close this one out

**Closed** 2024-05-24 05:59 UTC
Labels: bug, triage
